# Eureka Server 集群配置 server2
server:
  port: 8760

eureka:
  instance:
    hostname: peer2
  client:
#    默认
#    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone:
        http://peer1:8761/eureka/

spring:
  application:
    name: eureka-server

#  profiles: server2