spring:
  application:
    name: eureka-monitor-client

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  aggregator:
    clusterConfig: default
  app-config: eureka-ribbon-client, eureka-feign-client
  cluster-name-expression: new String("default")